server:
  port: 8080

rate-limiter:
  limits:
    user:
      capacity: 100
      refillRate: 100
      windowSeconds: 60

    ip:
      capacity: 200
      refillRate: 200
      windowSeconds: 60

    apiKey:
      capacity: 500
      refillRate: 500
      windowSeconds: 60
